### ISSUE TITLE
自列用例一栏需要自己创建fileupload文件夹，不然会报500错

### ISSUE THREAD

**Issue by JiangtaoXH** [youzan/bugCatcher#1]
![image](https://user-images.githubusercontent.com/18436285/30902253-2beb910a-a39d-11e7-9ae4-b29dd9ceff10.png)

**Comment by JiangtaoXH** [comment]
发现是windows系统才需要，自己关闭啦，不过希望也能加个bat文件，哈哈，我是用windows的菜鸟

**Comment by Celstmanboy** [comment]
这个大神能否再给点详细的解释下，自己创建fileupload文件夹后还是报了500的错误

**Comment by canyuns** [comment]
上面截图并没有说和fileupload有关, 好像是JDBC连接的问题.
@Celstmanboy 你的问题我猜是因为上传了同名文件导致的, 这个同名文件去重当时由于时间仓促并没有支持,抱歉

**Comment by canyuns** [comment]
@JiangtaoXH Windows上我没测试过, fileupload文件夹是使用Linux的shell创建的(mkdir ~/fileupload), Windows肯定是不支持这个shell的了,所以这个问题可以close了?

**Comment by JiangtaoXH** [comment]
截图截错了，windows下确实需要自己建fileupload文件夹，可能还要改文件夹的权限

**Comment by canyuns** [comment]
赋予读写权限
