### ISSUE TITLE
cant't login

### ISSUE THREAD

**Issue by 0ct0cat** [youzan/bugCatcher#2]
the login api is recursion

**Comment by canyuns** [comment]
@0ct0cat what？detail is？

**Comment by 0ct0cat** [comment]
sorry，i forget to describe the problem.and i know the reason.
this is my mysql version
mysql  Ver 14.14 Distrib 5.5.58, for debian-linux-gnu (x86_64) using readline 6.3

when create db,will report error like
ERROR 1293 (HY000): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
ERROR 1293 (HY000): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

i modify the sql like
createtime TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
updatetime TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW() COMMENT '更新时间',

it's ok now

**Comment by 0ct0cat** [comment]
but i find another error.
when i don't create ~/fileupload folder,the server will give a http code 500.

**Comment by canyuns** [comment]
When you initialize the project, you need to create a folder to place the uploaded files first. So, Please create a folder called 'fileupload' under your home directory first.
