### ISSUE TITLE
0用例分配报错

### ISSUE THREAD

**Issue by mzky** [youzan/bugCatcher#4]
查看用例-->不勾选用例-->点击分配-->报错

**Comment by canyuns** [comment]
不勾选用例, 那你分配什么 😳

**Comment by mzky** [comment]
就是刚搭建上 熟悉一下,^_^!
另外,这个三员权限适合研发自测形式的,我这里想要测试小组内部使用,要是能够分配所有权限给测试,在分配的时候,用例分配给需要的人

**Comment by canyuns** [comment]
可以的, 你可以参考已有的权限控制代码, 稍微改改就可以了
