### ISSUE TITLE
注册成功的用户为什么执行人下拉列表是空的，导致创建不了任务

### ISSUE THREAD

**Issue by ideallifeQA** [youzan/bugCatcher#5]
我按照你们的文档，环境部署成功了。
注册了测试、产品角色。
使用管理员admin 创建任务时，执行人下拉列表是空的。
**我的问题：**
请问执行人下拉列表是通过注册成功就自动会有吗？

**Comment by canyuns** [comment]
执行人的身份必须是开发, 所以你注册几个开发用户就有了
